name: caldec
description: "Calculateur intelligent DreamFlow"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  fl_chart: ^0.60.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  provider: ^6.1.1
  http: ^1.1.0
  uuid: ^3.0.7
  pdf: ^3.10.0
  printing: ^5.11.0
  share_plus: ^7.0.0
  petitparser: ^5.4.0
  expressions: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/
